### ISSUE TITLE
Delete Operation

### ISSUE THREAD

**Issue by DJuego** [xorz57/forest#62]
Thank you for sharing your library, @xorz57 ! 

I admit that I have not used it yet, but it looks splendid.  I just wanted to ask you why you have discarded the delete operation in your implementation until now. Delete/Remove nodes seems a operation very convenient... Maybe it's particularly complex...?

Thanks again!

DJuego

**Comment by xorz57** [comment]
@DJuego Hello. I am pleased that you like the library 😃. The delete operation has been put on hold because it's fairly complex to rebalance the trees after deleting a node. I did not just want to delete the subtree from the node to be deleted. I wanted to keep the subtree intact and rebalance the entire tree. That's why I have not implemented it.

If you are interested in implementing the `delete` or the `delete-subtree` operations you can make a PR.

I hope this answers your question. Feel free to reach me out here for any further questions and I would like to hear your feedback when you get the chance to use the library.

George Fotopoulos
